
[WorldGen]
	#Raritanium Ore Gen
	raritaniumOreGen = true
	#Raritanium Veins Per Chunk
	raritaniumOreVeinsPerChunk = 4
	#Raritanium Vein Size
	raritaniumVeinSize = 8
	#Raritanium Ore Min Y
	raritaniumOreGenMinY = 0
	#Raritanium Ore Max Y
	raritaniumOreGenMaxY = 30

[Economy]
	#Currency Name
	currencyName = "RC"
	#Bank Currency Capacity
	#The max amount of currency the Bank can store.
	#Range: 0 ~ 99999999
	bankCurrencyCapacity = 1000000
	#Cheap Money Bag Minimum Coins Amount
	#The minimum of the random amount of currency the Cheap Money Bag gives.
	#Range: 0 ~ 10000
	cheapMoneyBagMin = 10
	#Cheap Money Bag Maximum Coins Amount
	#The maximum of the random amount of currency the Cheap Money Bag gives.
	#Range: 0 ~ 10000
	cheapMoneyBagMax = 100
	#Rich Money Bag Minimum Coins Amount
	#The minimum of the random amount of currency the Rich Money Bag gives.
	#Range: 0 ~ 10000
	richMoneyBagMin = 75
	#Rich Money Bag Maximum Coins Amount
	#The maximum of the random amount of currency the Rich Money Bag gives.
	#Range: 0 ~ 10000
	richMoneyBagMax = 300

[Wallet]
	#Wallet Currency Capacity
	#The max amount of currency the Wallet can store.
	#Range: 0 ~ 99999999
	walletCurrencyCapacity = 1000000
	#Render Wallet Currency Overlay
	#Enable this render an overlay on your game screen showing your Wallet stats.
	walletOverlay = true
	#Wallet Currency Overlay Position
	#The position of the screen of the Wallet overlay
	#The valid values are {TOP_LEFT, TOP_RIGHT, BOTTOM_LEFT, BOTTOM_RIGHT}
	walletOverlayPosition = "TOP_LEFT"

["Link Book"]
	#Link Book Travel
	#Enable this allow traveling via Link Book or Link Portal.
	linkBookTravel = true
	#Link Book Portable Travel
	#Enable this allow traveling via Link Book while in hand.
	linkBookPortableTravel = true
	#Link Book Travel Cost Per Chunk
	#The cost per chunk when traveling with via Link Book or Link Portal. Set value to 0 for free travel.
	#Range: 0.0 ~ 10000.0
	linkBookTravelCostPerChunk = 1.0

[Misc]
	#Use Security
	#Disable this to allow everyone access to anyone's Blocks.
	useSecurity = true
	#Scaffold Max Height Teleport
	#0 to Disable. The max height you can teleport to the top or bottom of a scaffold.
	#Range: 0 ~ 256
	scaffoldMaxHeightTp = 256
	#Torch Placer Max Range
	#The max range the Torch Placer can place torches.
	#Range: 10 ~ 48
	torchPlacerMaxRange = 48
	#Blueprint Filler Max Scan Range
	#The max amount of Blueprint the Blueprint Filler can scan.
	#Range: 1 ~ 1000000
	blueprintFillerMaxScan = 100000
	#Blender Max Juice
	#The max height amount of juice the Blender can store.
	#Range: 0 ~ 1000000
	blenderMaxJuice = 1000
	#Trading Post Broadcasts
	#Disable this to disallow Players broadcasting their Trading Posts
	tradingPostBroadcasts = true
	#Trading Post Broadcast Delay
	#The amount of seconds before a Player can broadcasts their Trading Post.
	#Range: 0 ~ 3600
	tradingPostBroadcastDelay = 10

